/*
  This file is automatically generated. Any changes will be overwritten.
  Modify send.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { LabelComponent } from '@radzen/angular/dist/label';
import { AutoCompleteComponent } from '@radzen/angular/dist/autocomplete';
import { ListBoxComponent } from '@radzen/angular/dist/listbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';


export class SendGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('autocompleteVaelgReport') autocompleteVaelgReport: AutoCompleteComponent;
  @ViewChild('label1') label1: LabelComponent;
  @ViewChild('listboxVaelgSagsbehandler') listboxVaelgSagsbehandler: ListBoxComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('textarea0') textarea0: TextAreaComponent;
  @ViewChild('buttonSend') buttonSend: ButtonComponent;
  @ViewChild('button0') button0: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }

}
